plugins {
    id 'org.jetbrains.kotlin.jvm'
}
architectury {
    common rootProject.enabled_platforms.split(',')
}

sourceSets {
    test {
        kotlin.srcDir 'src/test/kotlin'
    }
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

    testImplementation "org.junit.jupiter:junit-jupiter-api:5.10.2"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.10.2"
    testImplementation "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
    
    // Kotest for property-based testing
    testImplementation "io.kotest:kotest-runner-junit5:5.8.0"
    testImplementation "io.kotest:kotest-assertions-core:5.8.0"
    testImplementation "io.kotest:kotest-property:5.8.0"
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(21)
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    testLogging {
        showStandardStreams = true
    }
}


