package tools.toolgen

import com.google.gson.GsonBuilder
import io.felipeandrade.metalmancy.Metalmancy.MOD_ID
import io.felipeandrade.metalmancy.items.ToolType
import java.io.File
import java.io.FileWriter

/**
 * Main generator for tool items, models, recipes, and advancements.
 * 
 * This generator creates all necessary files for tool-enabled materials:
 * - Tool item registration code
 * - Tool item models (JSON)
 * - Tool crafting recipes (JSON)
 * - Tool recycling recipes (smelting and blasting)
 * - Recipe advancements (JSON)
 * - Language entries (en_us.json)
 * 
 * Usage: ToolGen --out <output_directory>
 */
fun main(args: Array<String>) {
    var outDir = "build/generated"
    var i = 0
    while (i < args.size) {
        when (args[i]) {
            "--out" -> {
                outDir = args.getOrNull(i + 1) ?: outDir
                i++
            }
        }
        i++
    }

    println("[ToolGen] Starting tool generation...")
    println("[ToolGen] Output directory: $outDir")

    // Validate tool-enabled materials
    val invalidMaterials = ToolMaterials.validateToolEnabledMaterials()
    if (invalidMaterials.isNotEmpty()) {
        println("[ToolGen] WARNING: The following materials are invalid for tool generation:")
        invalidMaterials.forEach { material ->
            println("[ToolGen]   - ${material.name}: missing required parts or no tier mapping")
        }
    }

    // Filter to only valid materials
    val validMaterials = ToolMaterials.TOOL_ENABLED.filter { material ->
        ToolMaterials.hasRequiredParts(material) && ToolMaterials.getTierWithValidation(material) != null
    }

    println("[ToolGen] Generating tools for ${validMaterials.size} materials...")

    val gson = GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create()

    // Create output directories
    val assetsDir = File(outDir, "assets")
    val dataDir = File(outDir, "data")
    
    val itemModelsDir = dir(assetsDir, MOD_ID, "models", "item")
    val itemsDir = dir(assetsDir, MOD_ID, "items")
    val recipesDir = dir(dataDir, MOD_ID, "recipe")
    val advancementsDir = dir(dataDir, MOD_ID, "advancement", "recipe")
    val langDir = dir(assetsDir, MOD_ID, "lang")

    // Statistics
    var toolItemsGenerated = 0
    var modelsGenerated = 0
    var recipesGenerated = 0
    var advancementsGenerated = 0
    val languageEntries = mutableMapOf<String, String>()

    // Generate registration code
    val registrationCode = StringBuilder()
    registrationCode.appendLine("// Auto-generated tool item registration code")
    registrationCode.appendLine("// Generated by ToolGen")
    registrationCode.appendLine()

    // Generate tools for each material and tool type
    for (material in validMaterials) {
        for (toolType in ToolType.entries) {
            val tool = GeneratedTool(material, toolType)

            // Generate item model
            val itemModel = tool.generateItemModel()
            gson.writeJson(itemModelsDir, "${tool.unlocalizedName}.json", itemModel)
            modelsGenerated++

            // Generate item render
            val itemRender = tool.generateItemRender()
            gson.writeJson(itemsDir, "${tool.unlocalizedName}.json", itemRender)

            // Generate crafting recipe
            val craftingRecipe = ToolRecipes.generateCraftingRecipe(material, toolType)
            gson.writeJson(recipesDir, "${tool.unlocalizedName}.json", craftingRecipe)
            recipesGenerated++

            // Generate smelting recipe
            val smeltingRecipe = ToolRecipes.generateSmeltingRecipe(material, toolType)
            gson.writeJson(recipesDir, "${tool.unlocalizedName}_smelting.json", smeltingRecipe)
            recipesGenerated++

            // Generate blasting recipe
            val blastingRecipe = ToolRecipes.generateBlastingRecipe(material, toolType)
            gson.writeJson(recipesDir, "${tool.unlocalizedName}_blasting.json", blastingRecipe)
            recipesGenerated++

            // Generate recipe advancement
            val advancement = ToolRecipes.generateRecipeAdvancement(material, toolType)
            gson.writeJson(advancementsDir, "${tool.unlocalizedName}.json", advancement)
            advancementsGenerated++

            // Generate registration code
            registrationCode.appendLine(tool.generateRegistrationCode())
            registrationCode.appendLine()
            toolItemsGenerated++

            // Add language entry
            val localizedName = "${material.name.replaceFirstChar { it.uppercase() }} ${toolType.unlocalizedSuffix.replaceFirstChar { it.uppercase() }}"
            languageEntries["item.$MOD_ID.${tool.unlocalizedName}"] = localizedName
        }
    }

    // Write registration code
    val registrationFile = File(outDir, "ToolItemsRegistration.kt")
    registrationFile.writeText(registrationCode.toString())
    println("[ToolGen] wrote ${registrationFile.path}")

    // Generate language file
    generateLanguageFile(gson, langDir, languageEntries)

    // Copy files to resources
    println("[ToolGen] Copying generated files to resources...")
    val resourcesBase = File("src/main/resources")
    
    val copiedAssets = copyToResources(assetsDir, File(resourcesBase, "assets"))
    val copiedData = copyToResources(dataDir, File(resourcesBase, "data"))

    // Report statistics
    println()
    println("[ToolGen] ========================================")
    println("[ToolGen] Generation Complete!")
    println("[ToolGen] ========================================")
    println("[ToolGen] Tool items generated: $toolItemsGenerated")
    println("[ToolGen] Models generated: $modelsGenerated")
    println("[ToolGen] Recipes generated: $recipesGenerated")
    println("[ToolGen] Advancements generated: $advancementsGenerated")
    println("[ToolGen] Language entries: ${languageEntries.size}")
    println("[ToolGen] Files copied to resources: ${copiedAssets + copiedData}")
    println("[ToolGen] ========================================")
}

/**
 * Creates a directory and all necessary parent directories.
 */
private fun dir(base: File, vararg parts: String): File {
    var f = base
    for (p in parts) f = File(f, p)
    if (!f.exists()) f.mkdirs()
    return f
}

/**
 * Writes a JSON object to a file.
 */
private fun com.google.gson.Gson.writeJson(dir: File, fileName: String, json: com.google.gson.JsonObject) {
    val out = File(dir, fileName)
    FileWriter(out).use { w -> toJson(json, w) }
    println("[ToolGen] wrote ${out.path}")
}

/**
 * Generates the language file (en_us.json) with tool localized names.
 */
private fun generateLanguageFile(
    gson: com.google.gson.Gson,
    langDir: File,
    entries: Map<String, String>
) {
    val langFile = File(langDir, "en_us.json")
    
    // Load existing language file if it exists
    val existingEntries = if (langFile.exists()) {
        try {
            val existingJson = gson.fromJson(langFile.readText(), com.google.gson.JsonObject::class.java)
            existingJson.entrySet().associate { it.key to it.value.asString }
        } catch (e: Exception) {
            println("[ToolGen] WARNING: Failed to load existing language file: ${e.message}")
            emptyMap()
        }
    } else {
        emptyMap()
    }
    
    // Merge with new entries (new entries take precedence)
    val mergedEntries = existingEntries + entries
    
    // Create JSON object
    val langJson = com.google.gson.JsonObject()
    mergedEntries.entries.sortedBy { it.key }.forEach { (key, value) ->
        langJson.addProperty(key, value)
    }
    
    // Write to file
    FileWriter(langFile).use { w -> gson.toJson(langJson, w) }
    println("[ToolGen] wrote ${langFile.path}")
}

/**
 * Recursively copies all files from source directory to target directory,
 * preserving directory structure.
 */
private fun copyToResources(sourceDir: File, targetDir: File): Int {
    if (!sourceDir.exists() || !sourceDir.isDirectory) {
        println("[ToolGen] WARNING: Source directory does not exist: ${sourceDir.path}")
        return 0
    }
    
    if (!targetDir.exists()) {
        targetDir.mkdirs()
        println("[ToolGen] Created target directory: ${targetDir.path}")
    }
    
    var copiedCount = 0
    
    sourceDir.walkTopDown().forEach { file ->
        if (file.isFile) {
            val relativePath = file.relativeTo(sourceDir)
            val targetFile = File(targetDir, relativePath.path)
            
            // Create parent directories if needed
            targetFile.parentFile?.mkdirs()
            
            try {
                file.copyTo(targetFile, overwrite = true)
                println("[ToolGen] Copied: ${file.path} → ${targetFile.path}")
                copiedCount++
            } catch (e: Exception) {
                println("[ToolGen] WARNING: Failed to copy ${file.path}: ${e.message}")
            }
        }
    }
    
    return copiedCount
}
